import random
from z3 import *

class ConcolicEngine:
    def __init__(self, program_function):
        self.program_function = program_function
        self.symbolic_input = []
        self.concrete_input = []
        self.constraints = []

    def execute_concrete(self, concrete_input):
        self.concrete_input = concrete_input
        # Concrete execution of the program
        return self.program_function(*concrete_input)

    # def execute_symbolic(self, symbolic_input):
    #     self.symbolic_input = symbolic_input
    #     # Symbolic execution of the program (here we assume simple integer operations)
    #     return self.program_function(*symbolic_input)

    def add_constraint(self, constraint):
        self.constraints.append(constraint)

    def solve_constraints(self):
        solver = Solver()
        for constraint in self.constraints:
            solver.add(constraint)
        if solver.check() == sat:
            model = solver.model()
            list_vars = [model.eval(var).as_long() for var in self.symbolic_input]
            return list_vars
        else:
            print("No solution found.")
            return None

    def symbolic_execution(self, concrete_input):
        self.symbolic_input = [Int(f"input_{i}") for i in range(len(concrete_input))]
        # self.execute_symbolic(symbolic_input)
        
        # for i, concrete_value in enumerate(concrete_input):
        self.add_constraint(self.symbolic_input[0] > 10)
        self.add_constraint(self.symbolic_input[1] == 5)
        
        return self.symbolic_input

    def concolic_test(self, concrete_input):
        print("Concrete input:", concrete_input)

        # 1. Concrete execution
        concrete_output = self.execute_concrete(concrete_input)
        print("Concrete output:", concrete_output)

        # 2. Symbolic execution to generate constraints
        symbolic_input = self.symbolic_execution(concrete_input)

        # 3. Solve constraints to find new inputs that will take a different path
        new_inputs = self.solve_constraints()
        if new_inputs is not None:
            print("New input generated by solver:", new_inputs)
            return new_inputs
        else:
            print("No new input found.")
            return None

# Simple example program with branches
def example_program(x, y):
    if x > 10:
        return x + y
    else:
        return x - y

# Instantiate ConcolicEngine with the example program
concolic_engine = ConcolicEngine(example_program)

# Run concolic testing with a concrete input
concrete_input = [5, 3]  # Concrete input for testing
new_input = concolic_engine.concolic_test(concrete_input)

if new_input:
    print("Generated new input to explore different path:", new_input)
